version: "3.7"

services:
  jaeger-collector:
    image: jaegertracing/jaeger-opentelemetry-collector:latest
    command: []
    restart: always
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elastic:elastic@host.docker.internal:9200
    ports:
      # Used by jaeger-agent to send spans in model.proto format
      - 14250:14250
      # Admin and healthz
      - 14269:14269

